global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'mqtt-solution'
    static_configs:
      - targets: ['mqtt.solution:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'http2-solution'
    static_configs:
      - targets: ['http2.solution:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'grpc-solution'
    static_configs:
      - targets: ['grpc.solution:80']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'oracle'
    static_configs:
      - targets: ['oracle:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']